### ISSUE TITLE
Polish README

### ISSUE THREAD

**Issue by untemps** [untemps/svelte-readotron#19]
The documentation stood in the README file, like this issue description, has been written by a typical french guy who strongly need help to make it right.
If a native english dude wants to contribute, s.he would be warmly thanked.

**Comment by gage117** [comment]
Native English speaker here; I read through the whole README and to be honest I can't find anything that I would change. The English in the README is very good, I wouldn't even have been able to tell you aren't a native speaker!

Were you just looking for someone who speaks it natively to give it a glance and see if there's anything obviously wrong or is there something specifically in the README that made you feel it should be taken a peek at by an English speaker so I can take a closer peek?

**Comment by untemps** [comment]
Well I guess if you have not even noticed the README was written by a non-native english speaker is a good start.

Here are few examples of what I think may be improved:
- Enhancing global vocabulary.
- Finding an alternative to the 'use' verb which I tend to overuse.
- Correcting the expression `If the lang is not one of the listed ones or is undefined, the default value will be used.` which seems to be quite clumsy.

**Comment by gage117** [comment]
The global vocabulary seemed pretty good so someone who's even better at English than I am could probably find some minor improvements, but regardless it gets the ideas across as-is.

I did find a couple things to reword a bit and changed the requested expression in your third bullet. Feel free to give it a look over and let me know if you want anything about my wording changed!
