### ISSUE TITLE
Need a way to obtain the estimated time without the need of the change event

### ISSUE THREAD

**Issue by webJose** [untemps/svelte-readotron#51]
Hello, and thank you for your efforts.

I would like to know if there is any way in which I can obtain the word count and estimated reading time in cases where I there will be no scrolling.  I basically just need the reading time calculation.  As a matter of fact, I don't even need a user interface or display of any kind.

**Comment by untemps** [comment]
Hey, you probably noticed you may use the [@untemps/read-per-minute](https://github.com/untemps/read-per-minute) package for this ;)
